import React from "react";
import {
  SiPython,
  SiReact,
  SiVuedotjs,
  SiNodedotjs,
  SiPostgresql,
  SiDocker,
  SiAmazon,
  SiTypescript,
  SiGit,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiSass,
  SiVite,
  SiWebpack,
  SiJest,
  SiTestinglibrary,
  SiCypress,
  SiAndroid,
  SiApple,
  SiSwift,
  SiKotlin,
  SiFlutter,
  SiDart,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiPandas,
  SiNumpy,
  SiKeras,
  SiOpencv,
  SiTerraform,
  SiKubernetes,
  SiAnsible,
  SiFigma,
  SiAdobe,
  SiJira,
  SiSolidity,
  SiEthereum,
  SiChainlink,
  SiSelenium,
  SiJunit5,
  SiUnity,
  SiUnrealengine,
  SiBlender,
} from "react-icons/si";
import {
  FaJava,
  FaRust,
  FaShieldAlt,
  FaAngular,
  FaVuejs,
} from "react-icons/fa";
import {
  Database,
  Code,
  Layers,
  Smartphone,
  BrainCircuit,
  Cloud,
  Shield,
  Milestone,
  Briefcase,
  Users,
  Link as LinkIcon,
  Lock,
  Book,
  Gamepad2,
  GitMerge,
  Server,
  Braces,
  Target,
  Star,
  Award,
  Zap,
} from "lucide-react";

const iconMap: { [key: string]: React.ElementType } = {
  // Frameworks
  React: SiReact,
  Angular: FaAngular,
  Vue: FaVuejs,
  // Languages
  Python: SiPython,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  Java: FaJava,
  Rust: FaRust,
  // Backend
  Database,
  Server,
  PostgreSQL: SiPostgresql,
  "Node.js": SiNodedotjs,
  // Generic
  Code,
  Braces,
  Book,
  Layers,
  Smartphone,
  BrainCircuit,
  Cloud,
  Shield,
  Milestone: Target,
  Briefcase,
  Users,
  Link: LinkIcon,
  Lock,
  Gamepad2,
  GitMerge,
  start: Zap,
  skill: Book,
  optional: Star,
  advanced: Award,
  project: Milestone,
  Default: Code,
};

export const getIcon = (iconName: string | undefined): React.ElementType => {
  if (!iconName) return iconMap.Default;
  return iconMap[iconName] || iconMap.Default;
};
